version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "enhancement"
      - "housekeeping"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "enhancement"
      - "housekeeping"